### PR TITLE
Make the header search field required in the block plugin rather than using a hook_form_alter

### LINKED ISSUE #6: Empty error status message displayed on pages
With the new theme there's an empty error status message displayed across the top of every page. Turns out this is because we're hook_form_altering the search block to make it required.

Commenting out this like fixes the issue, but means that people can submit empty searches which was not wanted when specifying this: https://github.com/localgovdrupal/localgov_search/blob/d01f3fbe445751547bb9a9eb4019dbd9c18f880d/localgov_search.module#L98

Rather than using a hook_form_alter to make a search term required in the header search block, it can be set in the block plugin code and this solves the issue.

### PR DESCRIPTION
**Pull request by stephen-cox**
Closes #6

### CODE REVIEW

**Comment by stephen-cox** [comment]
The issue (#6) this fixes has been reported in Slack by someone demoing LGD. Tagging more reviewers as getting this fixes is high priority.

**Comment by ekes** [comment]
If we're placing the form anyway it makes sense to edit the form directly ourselves.

I'm just baffled why hook_form_alter would cause an empty message, and adding it to the form wouldn't?

**Comment by stephen-cox** [comment]
> I'm just baffled why hook_form_alter would cause an empty message, and adding it to the form wouldn't?

Same here - I'm thinking there's some sort of extra processing going on either before the search form gets form altered, but haven't spent much time delving into what's going on

**Comment by ekes** [comment]
Well if it's high priority and works when it's on the form when first passed in...

**Review by ekes — APPROVED** [review]

**Comment by finnlewis** [comment]
Well if @ekes is happy, merge it!

**Pull request merged**
