### PR TITLE
Fix for #42.

### PR DESCRIPTION
**Pull request by ekes**

### CODE REVIEW

**Comment by ekes** [comment]
If someone can double check this. I just realized I'm not 100% sure that module exists is returning the correct value when it has just been enabled in the previous update, my db might not have been clean by that point.

**Review by andybroomfield — APPROVED** [review]
Works for me (the error message about missing schema version is cleared.

I'm still seeing an error `Undefined variable $filename UpdateDBCommands.php` but I think this is to do with entity usage not this issue.

**Comment by ekes** [comment]
My hunch was correct it wasn't working if you ran both in the same update. This version should still work if you ran 8001 first and then 8002, but also if you are running them in one update.
 @andybroomfield this version should still work for you?

**Comment by andybroomfield** [comment]
````
// Requirements check reports errors. Do you wish to continue?: yes.           

 ----------- ----------- --------------- -------------------------------------- 
  Module      Update ID   Type            Description                           
 ----------- ----------- --------------- -------------------------------------- 
  facets      8012        hook_update_n   8012 - Update facet block caching     
                                          for the views with "Search API tag    
                                          or time" cache.                       
  localgov_   8007        hook_update_n   8007 - Directories Search API         
  directori                               database becomes its own module.      
  es                                                                            
  localgov_   8008        hook_update_n   8008 - Add schema version for         
  directori                               Directories Search API DB module.     
  es                                                                            
  localgov_   8001        hook_update_n   8001 - Sitewide search database       
  search                                  configuration moved to a new module,  
                                          enable it.                            
  localgov_   8002        hook_update_n   8002 - Add schema version for         
  search                                  Sitewide Search API DB module.        
````

Both updates work fine @ekes and I see localgov_search_db and localgov_directories_db with a schema version of 8000.

**Pull request merged**
